# Generated by Django 4.1.7 on 2023-02-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
