# Generated by Django 4.1.7 on 2023-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
